### PR TITLE
A GitHub Action to build the book

### PR DESCRIPTION
**Pull request by skuzzymiglet**
It's based on the README - it [fails](https://github.com/skuzzymiglet/openbook/runs/568689865?check_suite_focus=true) but I think it would be a good tool to keep stuff working

### CODE REVIEW

**Comment by veltzer** [comment]
I like this idea a lot.

**Comment by skuzzymiglet** [comment]
Could you look at the log to fix the error? Because the version in Ubuntu 18.04 is the one in the README: https://packages.ubuntu.com/bionic/lilypond

**Comment by skuzzymiglet** [comment]
Hey there, will this PR be merged, or does it need fixing? I think keeping the build in check is important, even if it fails. 

Another possibility is using artifacts to publish the resulting PDFs on each push (that is, once it succeeds)

**Comment by veltzer** [comment]
It's integrated and I made it work. Thank you for your efforts. They are appreciated.
The artifacts are part of the repo and I use the in the github.io page for the project.

**Comment by veltzer** [comment]
I don't know if you noticed but now the book is building on a matrix of 6 different systems (two ubuntus x 3 python versions). And I have a badge of building on the front README.md. This is all thanks to you. Thank you again.

**Comment by skuzzymiglet** [comment]
You're welcome! GitHub Actions is so flexible. The ideal automation
platform in my opinion. Why is there `build_cont`?

**Comment by veltzer** [comment]
build builds on ubuntu released and various versions of python.
build_cont builds on containers including 20.04 which is still not supported as os by github.
Just to cover all bases.

**Pull request merged**
